### ISSUE TITLE
How to daemonize celery workers

### ISSUE THREAD

**Issue by athopen** [gofynd/flask-full#3]
Hi,
I am trying to configure the deamonization according to this documentation (http://docs.celeryproject.org/en/latest/userguide/daemonizing.html?highlight=celeryd#example-django-configuration) but i have no idea how to specify the command (python manage.py celery_worker) correctly.

Could you please provide a documentation for that?

Thanks

**Comment by neerajshukla1911** [comment]
@andreaspenz you can deamonize celery using systemd in ubuntu 16.04 or upstart in ubuntu 14.04

**Comment by athopen** [comment]
@neerajshukla1911 Thanks for your quick response. In the celery documentation (http://docs.celeryproject.org/en/latest/userguide/daemonizing.html#usage-systemd) there is a sample systemd service-file with the following line

`ExecStart=/bin/sh -c '${CELERY_BIN} multi start ${CELERYD_NODES} \
  -A ${CELERY_APP} --pidfile=${CELERYD_PID_FILE} \
  --logfile=${CELERYD_LOG_FILE} --loglevel=${CELERYD_LOG_LEVEL} ${CELERYD_OPTS}'
ExecStop=/bin/sh -c '${CELERY_BIN} multi stopwait ${CELERYD_NODES} \`

Since the worker is a cli-command i could not provide the -A (app) argument. How could i archive the same functionality with your project?

**Comment by neerajshukla1911** [comment]
Replace bin/sh -c '${CELERY_BIN} multi start ${CELERYD_NODES} \ -A ${CELERY_APP}  - - with python manage.py celery

**Comment by athopen** [comment]
Thanks @neerajshukla1911 for the hint :+1: 
This is my final file:


```
[Unit]
Description=Celery Worker xyz
After=network.target

[Service]
Type=oneshot
User=celery
Group=celery
Restart=no
WorkingDirectory=/var/www/html/xyz/
ExecStart=/bin/sh -c '/usr/bin/python3 manage.py celery_worker --queues=xyz --concurrency=8 --logfile=temp/xyz.log'

[Install]
WantedBy=multi-user.target
```
